# Generated by Django 5.1 on 2025-06-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='course_id', help_text='Unique identifier for the course', max_length=20, unique=True),
        ),
    ]
