# Generated by Django 5.1 on 2025-06-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text="e.g. A1'CSE-24, B2'CSE-23", max_length=100, unique=True),
        ),
    ]
