# Generated by Django 5.1 on 2025-06-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Computer Science, Electronics', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(default=1, help_text='Year of study, e.g. 1 for first year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=1, help_text='e.g. Computer Science, Electronics', on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
            preserve_default=False,
        ),
    ]
