# Generated by Django 5.1 on 2025-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_branch_student_year_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(help_text='Year of study, e.g. 1 for first year'),
        ),
    ]
