# Generated by Django 5.1 on 2025-06-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcomponent',
            name='course_assignment',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignment', to='api.courseassignment'),
        ),
    ]
